import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/Provider';
import { ReduxProvider } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Horseless Sawari',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Provider>
        <body className={inter.className}>
          <Navbar />
          <main>
            <ReduxProvider>{children}</ReduxProvider>
          </main>
          <Footer />
          <Toaster />
        </body>
      </Provider>
    </html>
  );
}
